In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
# Leitura dos dados

data = pd.read_csv('H:/Meu Drive/10º SEMESTRE (2023_2)/Redes_Neurais_Artificiais_ET42D/EPC3/data_36_RNA.csv')

In [21]:
data

x1      x2       x3  d
0  -0.6508  0.1097   4.0009 -1
1  -1.4492  0.8896   4.4005 -1
2   2.0850  0.6876  12.0710 -1
3   0.2626  1.1476   7.7985  1
4   0.6418  1.0234   7.0427  1
5   0.2569  0.6730   8.3265 -1
6   1.1155  0.6043   7.4446  1
7   0.0914  0.3399   7.0677 -1
8   0.0121  0.5256   4.6316  1
9  -0.0429  0.4660   5.4323  1
10  0.4340  0.6870   8.2287 -1
11  0.2735  1.0287   7.1934  1
12  0.4839  0.4851   7.4850 -1
13  0.4089 -0.1267   5.5019 -1
14  1.4391  0.1614   8.5843 -1
15 -0.9115 -0.1973   2.1962 -1
16  0.3654  1.0475   7.4858  1
17  0.2144  0.7515   7.1699  1
18  0.2013  1.0014   6.5489  1
19  0.6483  0.2183   5.8991  1
20 -0.1147  0.2242   7.2435 -1
21 -0.7970  0.8795   3.8762  1
22 -1.0625  0.6366   2.4707  1
23  0.5307  0.1285   5.6883  1
24 -1.2200  0.7777   1.7252  1
25  0.3957  0.1076   5.6623 -1
26 -0.1013  0.5989   7.1812 -1
27  2.4482  0.9455  11.2095  1
28  2.0149  0.6192  10.9263 -1
29  0.2012  0.2611   5.4631  1

In [22]:
# Separacao dos dados

x1 = data['x1'].copy()
x2 = data['x2'].copy()
x3 = data['x3'].copy()
X = pd.concat([x1, x2, x3], axis=1)

y = data['d'].copy()

In [20]:
# Normalizacao dos dados segundo escala minmax

def normalizacao(data):

    min = data.values.min()
    max = data.values.max()

    data_norm = data.copy()

    for j in data.columns:

        for i in data.index:

            x = data.loc[i, j]

            # x_norm = (x - min) / (max - min)

            x_norm = x / max

            data_norm.loc[i, j] = x_norm

    return data_norm

In [23]:
X_norm = normalizacao(X)

In [24]:
# Adiciona coluna do limiar de ativacao = -1 (bias) no conjunto de dados
 
X_norm['bias'] = -1

In [25]:
X_norm

x1        x2        x3  bias
0  -0.053914  0.009088  0.331447    -1
1  -0.120056  0.073697  0.364551    -1
2   0.172728  0.056963  1.000000    -1
3   0.021755  0.095071  0.646053    -1
4   0.053169  0.084782  0.583440    -1
5   0.021282  0.055753  0.689794    -1
6   0.092412  0.050062  0.616734    -1
7   0.007572  0.028158  0.585511    -1
8   0.001002  0.043542  0.383696    -1
9  -0.003554  0.038605  0.450029    -1
10  0.035954  0.056913  0.681692    -1
11  0.022658  0.085221  0.595924    -1
12  0.040088  0.040187  0.620081    -1
13  0.033875 -0.010496  0.455795    -1
14  0.119220  0.013371  0.711151    -1
15 -0.075512 -0.016345  0.181940    -1
16  0.030271  0.086778  0.620147    -1
17  0.017762  0.062257  0.593977    -1
18  0.016676  0.082959  0.542532    -1
19  0.053707  0.018085  0.488700    -1
20 -0.009502  0.018573  0.600075    -1
21 -0.066026  0.072861  0.321117    -1
22 -0.088021  0.052738  0.204681    -1
23  0.043965  0.010645  0.471237    -1
24 -0.101069  0.064427  0.142921    -1
25  0.032781  0.008914  0.469083    -1
26 -0.008392  0.049615  0.594913    -1
27  0.202817  0.078328  0.928631    -1
28  0.166921  0.051296  0.905169    -1
29  0.016668  0.021630  0.452581    -1

In [ ]:
# Treinamento da rede neural

In [8]:
# valor maximo de epocas
MAX_EPOCA = 10000

# Taxa de aprendizado
n = 0.01

# Pesos iniciais (wi) e ajustados/finais (wf)
wi = pd.DataFrame(columns=['w0', 'w1', 'w2', 'w3'])
wf = pd.DataFrame(columns=['w0', 'w1', 'w2', 'w3'])

In [9]:
def func_ativacao(u):

    n = len(u)

    # Funcao Degrau Bipolar (-1;1)
    g = np.full(n, 1)

    # Verificacao: se u < 0, y = -1
    for i in range(n):

        if u[i] < 0:
            
            g[i] = -1

    return g

In [10]:
def treinamento(n, X_norm, wi, wf, MAX_EPOCA, y):

    y = np.array(y)

    for n_treino in range(5):

        print('-'*30)
        print(f'Treinamento numero: {n_treino}')
        print('-'*30)
        
        # Pesos aleatorios entre 0 e 1 do treinamento
        w = np.random.rand(4, 1)
        
        print(f'Pesos iniciais aleatorios: \n {w}')

        # Salva na tabela wi
        wi.loc[n_treino, :] = w[:, 0]

        # Contador de epocas
        epoca = 0

        print('-'*30)
        while(epoca < MAX_EPOCA):

            # Multiplicacao dos dados de entrada e bias (X_norm) pelos pesos (w)
            u = X_norm.dot(w)

            # Matriz resultante da multiplicacao das entradas pelos pesos (xn*wn) em formato de vetor
            u = np.array(u)

            # Verificacao do sinal de saida pela funcao de ativacao
            y_calc = func_ativacao(u)

            # Se os resultados calculados sao os mesmo que a saida
            if np.all(y_calc == y):

                wf.loc[n_treino, :] = w[:, 0]

                epoca = epoca + 1

                print(f'Convergência em {epoca} épocas')
                print(f'Pesos finais: \n {w}')

                break
            
            # Regra de Hebb
            else:

                erro = y - y_calc

                x_T = X_norm.T

                x_T_erro = x_T.dot(erro)
                
                n_x_T_erro = n*x_T_erro

                n_x_T_erro = n_x_T_erro.to_numpy().reshape(-1, 1)
                
                w = w + n_x_T_erro

                epoca = epoca + 1

    return wi, wf

In [ ]:
# Teste da Rede Neural

In [14]:
data_teste = pd.read_csv('H:/Meu Drive/10º SEMESTRE (2023_2)/Redes_Neurais_Artificiais_ET42D/EPC3/data_teste_36_RNA.csv')

In [29]:
data_teste

x1      x2      x3
0 -0.3665  0.0620  5.9891
1 -0.7842  1.1267  5.5912
2  0.3012  0.5611  5.8234
3  0.7757  1.0648  8.0677
4  0.1570  0.8028  6.3040
5 -0.7014  1.0316  3.6005
6  0.3748  0.1536  6.1537
7 -0.6920  0.9404  4.4058
8 -1.3970  0.7141  4.9263
9 -1.8842 -0.2805  1.2548

In [30]:
X_teste_norm = normalizacao(data_teste)

In [31]:
X_teste_norm['bias'] = -1

In [32]:
X_teste_norm

x1        x2        x3  bias
0 -0.045428  0.007685  0.742355    -1
1 -0.097202  0.139656  0.693035    -1
2  0.037334  0.069549  0.721817    -1
3  0.096149  0.131983  1.000000    -1
4  0.019460  0.099508  0.781388    -1
5 -0.086939  0.127868  0.446286    -1
6  0.046457  0.019039  0.762758    -1
7 -0.085774  0.116564  0.546104    -1
8 -0.173160  0.088513  0.610620    -1
9 -0.233549 -0.034768  0.155534    -1

In [18]:
def teste(X, wf):

    X = np.array(X)

    wf_T = wf.transpose()
    wf_T = np.array(wf_T)

    u_teste = X.dot(wf_T)

    for j in range(5):

        print('-'*30)
        print(f'Teste numero: {j}')
        print('-'*30)

        y_teste = func_ativacao(u_teste[:,j])

        print(y_teste)

    return u_teste

In [33]:
resultado = teste(X_teste_norm, pesos_finais)

------------------------------
Teste numero: 0
------------------------------
[-1 -1 -1  1 -1  1 -1  1 -1 -1]
------------------------------
Teste numero: 1
------------------------------
[-1 -1 -1 -1 -1  1 -1  1 -1 -1]
------------------------------
Teste numero: 2
------------------------------
[-1 -1 -1 -1 -1  1 -1  1 -1 -1]
------------------------------
Teste numero: 3
------------------------------
[-1 -1 -1 -1 -1  1 -1 -1 -1 -1]
------------------------------
Teste numero: 4
------------------------------
[-1 -1 -1  1 -1  1 -1  1 -1 -1]


In [41]:
# Aplicacao da rede neural

def app(n, X_norm, wi, wf, MAX_EPOCA, y, X_teste_norm):

    pesos_inicias, pesos_finais = treinamento(n, X_norm, wi, wf, MAX_EPOCA, y)

    resultado = teste(X_teste_norm, pesos_finais)

    return pesos_inicias, pesos_finais, resultado

In [46]:
pesos_inicias, pesos_finais, resultado = app(n, X_norm, wi, wf, MAX_EPOCA, y, X_teste_norm)

------------------------------
Treinamento numero: 0
------------------------------
Pesos iniciais aleatorios: 
 [[0.11481724]
 [0.52191675]
 [0.03966885]
 [0.03737516]]
------------------------------
Convergência em 1244 épocas
Pesos finais: 
 [[ 2.8261313 ]
 [ 4.73788792]
 [-1.38767851]
 [-0.48262484]]
------------------------------
Treinamento numero: 1
------------------------------
Pesos iniciais aleatorios: 
 [[0.28255925]
 [0.93687396]
 [0.00111858]
 [0.97026232]]
------------------------------
Convergência em 1233 épocas
Pesos finais: 
 [[ 2.79607976]
 [ 4.93256463]
 [-1.36768914]
 [-0.46973768]]
------------------------------
Treinamento numero: 2
------------------------------
Pesos iniciais aleatorios: 
 [[0.57259622]
 [0.06144014]
 [0.80504549]
 [0.01190619]]
------------------------------
Convergência em 1381 épocas
Pesos finais: 
 [[ 3.01873855]
 [ 4.36706785]
 [-1.40045414]
 [-0.50809381]]
------------------------------
Treinamento numero: 3
-----------------------------

In [47]:
pesos_inicias

w0        w1        w2        w3
0  0.114817  0.521917  0.039669  0.037375
1  0.282559  0.936874  0.001119  0.970262
2  0.572596   0.06144  0.805045  0.011906
3  0.610573  0.826965  0.067521  0.141054
4  0.052365  0.084554  0.884584  0.361271

In [48]:
pesos_finais

w0        w1        w2        w3
0  2.826131  4.737888 -1.387679 -0.482625
1   2.79608  4.932565 -1.367689 -0.469738
2  3.018739  4.367068 -1.400454 -0.508094
3  2.899826  4.569524 -1.403201 -0.498946
4  2.695296  4.609069 -1.326779 -0.458729